# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: git clone https://github.com/CayoOps/testingtf.git
  displayName: 'clunando repo'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    terraform init
    terraform plan
  displayName: 'Run a multi-line script'

